version: "3.7"

services:
  modsim:
    build: ./
    container_name: modsim
    image: modsim
    command: "tail -f /dev/null"
    volumes:
      - './data:/app/data'
      - './plotting_result:/app/plotting_result'