version: "3.7"

services:
  modsim:
    build: ./
    container_name: modsim
    image: modsim
    command: bash -c "cd app && ./build/src/run"
    volumes:
      - './data:/app/data'
      - './plotting_result:/app/plotting_result'