version: "3.7"

services:
  modsim:
    build: ./
    container_name: modsim
    image: modsim
    command: bash -c "cd app && ./build/src/run"
    volumes:
      - modsim-data:/app/data/
      - modsim-plotting-result:/app/plotting_result/

volumes:
  modsim-data:
    external: true
  modsim-plotting-result:
    external: true