#!/bin/bash
#SBATCH --time=23:59:00
#SBATCH --cpus-per-task=24
#SBATCH --mem=96000
#SBATCH --job-name=galaxy
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=s.evanghelides@student.rug.nl
#SBATCH --output=job-%j.log

srun ./run 1000000 1000000 1000
